import type { Card } from '../types/game'

export const cards: Card[] = [
  {
    id: 'fireball',
    name: 'Fireball',
    stats: { attack: 10, shield: 0, heal: 0, burn: 5, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic fire spell',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'spell',
  },
  {
    id: 'heal',
    name: 'Heal',
    stats: { attack: 0, shield: 0, heal: 10, burn: 0, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic healing spell',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'spell',
  },
  {
    id: 'shield',
    name: 'Shield',
    stats: { attack: 0, shield: 10, heal: 0, burn: 0, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic shield spell',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'tool',
  },
  {
    id: 'poison',
    name: 'Poison',
    stats: { attack: 0, shield: 0, heal: 0, burn: 0, poison: 5, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic poison spell',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'spell',
  },
  {
    id: 'sword',
    name: 'Sword',
    stats: { attack: 10, shield: 0, heal: 0, burn: 0, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic sword attack',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'weapon',
  },
  {
    id: 'armor',
    name: 'Armor',
    stats: { attack: 0, shield: 10, heal: 0, burn: 0, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'A basic armor defense',
    rarity: 1,
    baseCost: 10,
    cost: 10,
    type: 'armor',
  },
  {
    id: 'Obama',
    name: 'Friend',
    stats: { attack: 30, shield: 0, heal: 10, burn: 0, poison: 0, actionRate: 5 },
    level: 1,
    maxLevel: 5,
    description: 'The president',
    rarity: 1,
    baseCost: 10,
    cost: 30,
    type: 'friend',
  },
]
